apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: app-ingress
spec:
  rules:
  - host: master.boygruv.lc
    http:
      paths:
      - backend:
          serviceName: service-test-svc
          servicePort: 8010
        path: /app1
      - backend:
          serviceName: nginx-ingress
          servicePort: 18080
        path: /nginx_status

